apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-app2
  name: springboot-app2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: springboot-app2
  template:
    metadata:
      labels:
        app: springboot-app2
    spec:
      containers:
      - name: my-springboot-app2
        image: sreekanth143/java-web-app-docker:pde
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app2
    k8s-app: springboot-app2
  name: springboot-app2
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: springboot-app2
